### ISSUE TITLE
Second round of feedback

### ISSUE THREAD

**Issue by teenie-quaggard** [GSG-G7/sitspot#104]
Amazing job team!!! 🌈

This is the biggest scope that I have seen for a Tech for Better project, so well done! I am so impressed by how much you've managed to complete in just one month. With only three days of development left, I'd please like to prioritize the following. Please note that I will be talking with Katia later tonight and will make any amendments to this before tomorrow morning. Thank you!!!

## Priority

- [x] 1. The search functionality needs to be streamlined so that only countries and cities that are in the current database are displayed in the search dropdown. It will become really frustrating if a user comes to the site and searches for a country or a city a number of times and doesn't find any results! This means a country name should only be rendered if there is at least one approved Sitspot in the database. 

- [x] 2. When adding a new Sitspot, inputs for business name, country and city, and business type should be mandatory inputs (required)
![Screen Shot 2019-11-18 at 17 00 48](https://user-images.githubusercontent.com/37771591/69073308-17f19f00-0a25-11ea-96c3-912ef230f395.png)

- [x] 2. Following off of that, it would be great to have a **'Sorry, there are no Sitspots that match your search'** message that is rendered when no results are found.
![Screen Shot 2019-11-18 at 16 51 05](https://user-images.githubusercontent.com/37771591/69072524-b7ae2d80-0a23-11ea-98c1-2e42bd13344b.png)

3. At the moment, it doesn't seem like the search functionality works from the search results page. If I already have made a search and am looking at results, I should be able to make another search from the search result page so that I don't have to go back to the home page to make a search.

- [x] 4.  In FAQs, page crashes when clicking 
![Screen Shot 2019-11-18 at 17 07 37](https://user-images.githubusercontent.com/37771591/69073830-0c52a800-0a26-11ea-9d46-ede7111344e6.png)

- [x] 5. Ensure that images are optimised for web 

- [x] 6. Create handover documentation / user manual of how Airtable works for Katia

## Would be nice: 
- [x] We can also **remove the 'Would you like to add a new Sitpot?' link** that is displayed on the results page as there is already an 'Add your recommendation' button.
![Screen Shot 2019-11-18 at 16 53 50](https://user-images.githubusercontent.com/37771591/69072696-078cf480-0a24-11ea-8623-af1973079d77.png)

Nav menu should overlay the content, not push the content of the page down. It should also close automatically after someone has selected an option from the dropdown menu.
![Screen Shot 2019-11-18 at 17 04 56](https://user-images.githubusercontent.com/37771591/69073562-92baba00-0a25-11ea-98a5-75405768c59a.png)

- [x] Iphone5 search menu is a bit wonky. I would suggest stacking 'Stay', 'Eat and Drink' and 'Shop' instead of how it is now.
![Screen Shot 2019-11-18 at 17 14 45](https://user-images.githubusercontent.com/37771591/69074374-2476f700-0a27-11ea-930a-f1a32df47730.png)

**Comment by KatiaSitspot** [comment]
**Adding to Kristina’s points: PRIORITIES**

1.	### Country menu. 
To rephrase Kristina’s point: the dropdown menu for countries should only display the countries for which we have sitspots listed, with the number of sitspots,
example 1: United Kingdom (10)     (we might have 6 Stays, 4 Eats, and 0 Shop)

2.	### Adding a new recommendation – pic upload. 
To add to Kristina’s point, when adding a new recommendation, it’s important that adding a URL, and uploading a picture should be optional. Many users will NOT have a picture to upload, and we should let them submit a new recommendation regardless.

We are asking users to upload pictures at 2 different stages of the flow. To avoid confusing the users, we should explain our rational to the users:
a.	Picture upload at step 6. Here we are encouraging users to upload 1 picture. The objective is to ensure admins can identify the correct business. 
![image](https://user-images.githubusercontent.com/56404750/69108401-7130f100-0a6c-11ea-8faa-289b39605662.png)

The copy here needs to be changed from “Upload some pictures. It helps bring your recommendation to life, and makes it even more trustworthy!” to => 
“Upload 1 picture if you can. It will help us identify your sitspot. You will be able to upload more pictures at the end of the questionnaire”.
b.	Picture upload at the end of the Typeform. We want users to upload as many nice pictures as possible in order to bring their recommendations to life. Here I have already a description in Typeform that explains, so no change required.
![image](https://user-images.githubusercontent.com/56404750/69108420-80b03a00-0a6c-11ea-9ce5-389f00be191f.png)


### 3.	Same comment as Kristina

4.	.

### 5.	Same comment as Kristina

### 6.	Images optimised for web. Same comment. See screengrabs
a.	In “Add a recommendation / Step 1” - the picture is completely distorted on mobile (I am using an iphone 10)
![image](https://user-images.githubusercontent.com/56404750/69108164-be609300-0a6b-11ea-919d-e0c03139b888.png)

b.	On desktop, the images for each headers are cropped weirdly.
o Home => image ok
o Search => we just see a bit of the back of a person
![image](https://user-images.githubusercontent.com/56404750/69108201-ea7c1400-0a6b-11ea-8545-b6e3790a99ee.png)

o Add a recommendation => this is so cropped that we can’t identify what this is
![image](https://user-images.githubusercontent.com/56404750/69108236-f8ca3000-0a6b-11ea-967b-dc3d3bfbd12d.png)

o FAQ => we see someone’s hair
![image](https://user-images.githubusercontent.com/56404750/69108255-02ec2e80-0a6c-11ea-8071-d2d01d578d25.png)

o About us => the positioning is OK but I don’t like this picture. Can we swap for the lady facing the lake, or the girl with her dog?
![image](https://user-images.githubusercontent.com/56404750/69108316-28793800-0a6c-11ea-9e81-6c9229c3a691.png)


### 7.	Click to start your review. 
We have the same instructions repeated twice, with the copy  “We will now ask you to follow these (…) so warm thanks in advance”:
a.	I get it after I click “done” after step 7
![image](https://user-images.githubusercontent.com/56404750/69107978-219df580-0a6b-11ea-8580-141020bb0d69.png)
b.	Then I get it again when I click on “Click to start your review”, and start my recommendation in Typeform (with the SitSpot logo)  
![image](https://user-images.githubusercontent.com/56404750/69107990-2b275d80-0a6b-11ea-8a6c-7cbd67c82d0a.png)
=> please remove the 1st page 

### 8.	Actual sitspot entry
When I click on Slovenia + Stay, or Thailand + Stay I don’t have any results yet some have been entered in the database. Is it possible to add them in? 

Individual SitSpot page: I would need to see how the page looks for actual (not fake) sitspot recommendations: e.g. The Nest (accommodation recommended by Laura), W6 Garden (café recommended by SitSpotterInChief) , Hetu (shop recommended by GwenaGo),

**Comment by KatiaSitspot** [comment]
**### WOULD BE NICE**

### 1.	remove “Would you like to add a new sitspot?”  Same comment as Kristina

### 2.	Add a recommendation
On the instruction page after step 7:
a.	can you please change from “Click to start your review!” => to “**click to start your recommendation!**”
b.	as you have made the arrows orange, the copy needs to change to say “click on the **orange** arrows bottom right of the screen” (currently it says green).

### 3.	Copy change on the Typeform (Please let me know if you prefer that I do these copy changes myself)
•	For all 3 Typeforms (Stay, Eat and Shop), on the intro section, change “scroll up or click on the green arrows” to “scroll up or click on the **orange** arrows”.
•	For all 3 Typeforms (Stay, Eat and Shop), at section 3:
- The question should read:      **Now, <alias>, the following questions will ask you to select the positive sustainability practices that you noticed.** 💚
- As a description (so in grey), it should say:
**If there’s any criteria you are unsure about, just leave it out.
If none of them apply, click N/A.
In "Other", please add any other positive practices you noticed, or helpful suggestions you would like to provide to the business.**
•	For all 3 Typeforms, on the last question it should read
**You're a click away from submitting your recommendation. 
Please acknowledge that by submitting a recommendation to SitSpot, you agree to the following terms and conditions:** 


•	in the STAY Typeform, intro page, delete “and”  **5) write** a brief overall review.

•	in STAY Q11 and EAT Q12, solo traveler should be written **solo traveller**. Please note that I had added “**LGBT friendly**” as a an criteria in STAY

•	In the SHOP Typeform
     delete the description at questions 10, 11, 12

     Question 14, change the punctuation:
	**- Staff interaction: the staff
         - Staff knowledge: the staff
         - Championing the cause: the**

•	Question 15, change description from max 100 characters e.g. "insanely delicious fresh pasta, and an ocean view to remember"  To => **max 100 characters e.g. Cute zero waste bulk shop in Chiswick, London**
•	Question 22, can we change to “When did you **last** visit this place?”. The answer should NOT be MM DD YYYY, but instead **MM YYYY**

In EAT and SHOP Typeform
•	change “write a headline”, to **Give your recommendation a headline  📣**
•	Eat Q19, Shop Q16, Question should read  **Write your short overall recommendation**
And description:
**Tips: 
📝 You could mention additional sustainability credentials and feel-good aspects.
📝 You could summarise the ones that impressed you the most and made your visit truly memorable.
📝 You could also add constructive suggestions you would like to provide to the business.
📝 To be even more helpful, please share the context of your visit and recommend the type of customers this place would be most suited for.**
•	Eat Q20, Shop Q17. Change from hasn't given you permission to do so. To => **hasn't given you permission to share on this platform.**

### 4.	Keywords: we are missing some. I had shared a spreadsheet showing how each keyword is linked to a particular question in Typeform [](url) https://1drv.ms/x/s!AjYAThCZglCyxi3-cS29dXiTIb7j?e=de9PKy 

### 5.	Landing page – copy change
a.	Second paragraph, “**F**ind and recommend” Find is missing a capital F. 
b.	Can you display images from actual sitspots from the database instead of random beach images?

### 6.	About us – copy change
a.	Meet the founder. Can you please make those copy changes.
•	funding a **green** group
•	and **was** under-served
•	and **to** contribute to making
b.	Our Values
We are missing  **spaces** between each sentence.

### 7.	FAQ – copy change
a.	Can you please remove the last 3 words (for a chat) **The following Q&A should hopefully answer your questions. If not, get in touch at reviews@mysitspot.com** .
b.	There are typos in the sub-headers. It should read:
•	**What’s a sitspot?** (question 1)
•	I **stayed at** a place which has the worse (question 4). (My bad I had written “stayed in a place” which doesn’t sound right.)
•	I have **stayed at** an accommodation which ticked (question 8). Same as above

**Comment by KatiaSitspot** [comment]
### **QUESTIONS**

### 1.	**Freeze on mobiles**
When I filled in the Typeform on my mobile, the page often freezes, and then I get a page from Typeform (see screenshot). Do you have the same issue?
![image](https://user-images.githubusercontent.com/56404750/69109109-9de60800-0a6e-11ea-826b-d5219d0fbb9f.png)


### 2.	Search
Please confirm that users will be able to search:
a.	By just clicking search without selecting any criteria (i.e. it should bring up all results from the database)
b.	By selecting 1 country and getting sitspots from all types from that country
c.	By selecting 1 city and getting sitspots from all types from that city
d.	By selecting 1 country + 1 type (e.g. Slovenia + Stay)
e.	By selecting just 1 type e.g. Stay and getting all accommodations listed across all countries
f.	By selecting just 1 magical factor e.g. animal connection and getting all sitspots where users have selected that magical factor, across all countries and all types.
g.	By selecting 1 country, 1 city, and 1 magical factor
h.	Etc…

### 3.	Picture upload
In “add a recommendation / step 6”, and in the Typeform, Is there an option to edit the picture to rotate the picture?

**Comment by Amoodaa** [comment]
### About 4 in katia's
No, we aren't missing them, with our time limit and current capabilities with Airtable, we cant search based on all keywords, because of how they are extracted from different questions,
and those 7 that are available, we've been able to search based on them because each has their own field at the end of the table, those 7 are the 7 from section 4

**Comment by Amoodaa** [comment]
And as for point 8 in kaita's, when did u enter the Slovenia and Thailand?
if they were entered as a Typeform, then that must have happened before we connected Airtable and Typeform, but if that happened yesterday, I want to know more

**Comment by KatiaSitspot** [comment]
No i entered them before the 2 systems were connected 
Katia HERAULTM: 07825189550

**Comment by Amoodaa** [comment]
Ill check if i can take them into the airtable

**Comment by Amoodaa** [comment]
and 1 important question, there wasnt in the design any usage for the images uploaded in typeform, would you like to add a slider to each review, with the up to 10 images?

**Comment by KatiaSitspot** [comment]
The layout for the individual sitspot page that my designer created did include a slider at the top of the page for viewing all the pictures from the various reviewers. 
In my « Pages » document (or brief), i didn’t ask to allow users to upload a picture as part of the “sitspot ID” information. But I have seen that you have added this functionality (step 6). So in the flow that you have built, users can now upload pictures at 2 different stages (this is what i have explained on Github yesterday): at step 6 and then again at the end of the Typeform . As i said, this  would be bizarre and confusing to users, so we need to either remove this functionality at step 6/or in the Typeform, or add an explanation at step 6 (see my copy suggestion in my previous comment). 
And to clarify again: yes we absolutely need a slider so the user can view all the pictures that have been uploaded for that sitspot by all the users who have recommended it. Please don’t hesitate to let me know if it would be easier for us to discuss this issue over the phone?
Katia HERAULTM: 07825189550

**Comment by KatiaSitspot** [comment]
Hi @aminalakhsham and the team, I can see that you have implemented several of the changes we requested, which is awesome!
I wanted to flag a problem with the SEARCH dashboard. At first users will probably select quite a few criteria, and that won't bring results. We need to make it easy for them to find results.
For example, If I select United Kingdom + London + STAY, I get zero results. So I would like to select some criteria but I can't deselect London, and I can't deselect STAY. 
In the city menu, we should perhaps have a "blank" option, or a "select" option, that would neutralise my previous selection. It seems possible to neutralise the keywords that have been selected (by simply clicking again on them), but not to neutralise the type stya/eat/shop (we can't click again to deselect them)

![image](https://user-images.githubusercontent.com/56404750/69334099-e6a9e680-0c51-11ea-8e33-d652501d0853.png)
