### ISSUE TITLE
Kickoff

### ISSUE THREAD

**Issue by 11janci** [GSG-G7/sitspot#45]
Hi team,

I'm Jan, I will be helping you with the project as mentor. Some of you I think I already worked with in one of the previous sprints 🙂 

Have just one question, the readme states the following:
> As a user, I can save my basic info in my local storage to be sent with my reviews (not required to submit the form)

Why local storage and not the database? Will you allow to add reviews by users without an account?

No other comments yet as you're obviously just starting. The project structure looks good.

Looking forward to working with you!

**Comment by Amoodaa** [comment]
Yes there is no user login or registering

**Comment by Amoodaa** [comment]
and we are using airtable as the database, and Typeform as the form to show to the users

**Comment by Amoodaa** [comment]
https://developer.typeform.com/embed/ here is the Embed SDK,
but we found a react wrapper for it, and we are gonna use instead: https://www.npmjs.com/package/react-typeform-embed

and if we get the chance to evolve the backend from Airtable to a traditional DB, our resort would be using https://developer.typeform.com/webhooks/, but we are being careful because of the scope
