### ISSUE TITLE
Communication with Katia

### ISSUE THREAD

**Issue by teenie-quaggard** [GSG-G7/sitspot#5]
Hi @KatiaSitspot - I hope you are well! 
To give you a debrief, the team has been working hard on creating the dynamic version of the prototype. [You can find it here](https://www.figma.com/file/eHk8vhGnrd4qMBlm7nX9kE/SitSpot?node-id=0%3A1).

In terms of more technical things such as Typeform, they will not begin on these until they have finished the prototype. They are hoping to finish the prototype today so that they can have the full day to do sprint planning and research any technical spikes tomorrow.
I don't think there is any need to catch up today. I will post our User Testing Script in another issue so that you can take a look. Tomorrow, I will lead the user testing and you will take notes while we watch the users interact with the prototype online. We will ask the users to attempt to complete a few basic tasks to test the success of our UX/UI.

Thanks Katia!

**Comment by KatiaSitspot** [comment]
Thanks Kristina,When i click on the Figma link all i see are the static wireframes from Jim?
Shall i come in advance tomorrow? What time?BestKatia 
Katia HERAULTM: 07825189550

**Comment by teenie-quaggard** [comment]
@KatiaSitspot - you can click the play button at the top right hand corner of the Figma! That should bring you to a mobile view.

15 minutes before should be enough! We will be in the Outlandish offices, two floors above Space4 (same entrance as FAC, but a different buzzer).

**Comment by KatiaSitspot** [comment]
Hi,Figma seems yo work on my desktop (although the menu shows Jim’s layout, not the correct one). But on mobile this is what i see..
Lastly i have asked the users to click on the Google hang out link 5 min before their slot. To have a laptop, internet connection and mobile with them. Anything else?
See you at 2.45pm !Katia 


Katia HERAULTM: 07825189550

**Comment by KatiaSitspot** [comment]
Today I will concentrate on 
- creating a short  Typeform with the sitspots ID: business name, country, city, website, and business types (either accommodation, restaurant or shop)
- updating the Typeform for accommodation as per my conversation with Kristina: with the contributor profile and the accommodation questionnaire on one form.

**Comment by teenie-quaggard** [comment]
@KatiaSitspot - thanks for the update Katia! Please let us know when you are finished with the forms. :)

**Comment by teenie-quaggard** [comment]
@KatiaSitspot - One other question: when are we set to hear back from Jim with a finalised version?

**Comment by KatiaSitspot** [comment]
I have sent him the requested changes and told him that we need them done EOP MOnday

**Comment by KatiaSitspot** [comment]
Hi Kristina, 

Following your request I have started reworking the forms. The “sitspot ID form” is ready in Typeform.

The one for accommodations (which now includes the contributor profile infos) is nearly there but some logic jumps are faulty, I still need to play around with them on Monday.

**Comment by KatiaSitspot** [comment]
Hi @teenie-quaggard and @team!

Good news! After a few hours playing around with the logic jump functionality in Typeform, I can confirm that the 2 forms below are ready. I wanted to add logic jumps so that users can jump questions if they have already entered their contributor profile when they submitted their first recommendation, and could be sent the correct follow up questions for the specific "magical factor" they have selected, and could skip upload question if they don't upload any picture. Those are ready for you:
1. sitspot ID (final) - Katia
2. STAY Recommendation without sitspot ID (final) - Katia

I will then today/tomorrow work on:
3. EAT Recommendation without sitspot ID, and 
4. SHOP Recommendation without sitspot ID
and we will be done with Typeform. I understand that if I later on make changes to the copy it doesn't impact your flow?

Please let me know if all is clear or if you have questions. Thanks

**Comment by teenie-quaggard** [comment]
Hi @KatiaSitspot - thanks for the update!
I will double check with the team on whether or not updates to the form will update their process and will let you know. Thank you for all your work!

**Comment by KatiaSitspot** [comment]
I have updated the PAGES document to reflect the change of flow that you requested. It is now v7 https://1drv.ms/w/s!AjYAThCZglCyxVreKouNd6HX4TqN?e=ALXETA 

Latest design are saved here (no change since when I shared them with Kristina over the weekend). Latest prototype on Marvel https://marvelapp.com/7g2ah3f/screen/62531897  
and layouts at https://www.dropbox.com/s/j579fvubrg8dfw6/SitSpot%20web%20devs%2004%20-%20review%20pages.ai?dl=0   
I Please note they're not final and Jim the designer will finalise them in the coming days

**Comment by KatiaSitspot** [comment]
Design layout are now final and can be accessed at 👍 
https://www.dropbox.com/s/nj35lhj9np5r6v5/SitSpot%20web%20devs%2005.ai?dl=0

https://marvelapp.com/7g2ah3f/screen/62522592

**Comment by teenie-quaggard** [comment]
@aminalakhsham - just want to flag your attention to the resources that @KatiaSitspot has shared above!

**Comment by aminalakhsham** [comment]
why not add two separate menus for city and country?
why not add input for the place name?
@KatiaSitspot

**Comment by aminalakhsham** [comment]
@teenie-quaggard  thank you

**Comment by teenie-quaggard** [comment]
Hi @aminalakhsham ! I think Katia does want separate menus for city and country. Here is the example she shared in the Pages document:
https://www.holiable.com/lodging/hotel/

- place name does sound like a good idea, I think we can put that into stretch goals for now

**Comment by KatiaSitspot** [comment]
@teenie-quaggard and @aminalakhsham 
For the search (=dashboard):
- yes, we should have a field for country and a field for city. The designer has designed 1 combined field, but Kristina said the students could easily make it 2 fields
- as for place name: if you mean business name, e.g. "Hotel St Daniel", then I really don't think this is necessary. None of the travel platforms have this field in their search. Users rarely know in advance the name of the place they want to stay at
- last point. If possible, (maybe a stretch goal?). You'll notice that in the Typeform we are not asking users to enter the business address. This is because I felt that would be seen as tedious and might put some users off. However, during research, several users had said that this information would be useful to them. So it would be useful if admins could add this info so that it is visible on the "individual sitspot page"

**Comment by KatiaSitspot** [comment]
@aminalakhsham @teenie-quaggard 
in the PAGES v7 document, I have added
- top of the document,  the relevant links to design assets
- in the document under each specific page (right hand side column) the link to the relevant layouts for that page

**Comment by teenie-quaggard** [comment]
Hi @KatiaSitspot!
I have just finished the meeting with Amin. There were a few things that came up.

1. The team will be unable to use Typeform for the Sitspot info (adding a new place) because of a technicality. The team needs to access the ID of that individual Sitspot, in order to pass it to the associated recommendation and this is impossible using Typeform. The solution to this that the team will manually create a one page form (using your Typeform as the basis) so that they will have access to the Sitspot ID and can associate that to the recommendation 

2. We clarified that the Alias will be an input in the typeform, and that will be used to identify the same user across different reviews.

3.They wanted to let you know that the local storage part (saving the user info locally) will now be cancelled as it will be part of the typeform

4. They are clear that the search will be separate inputs for country and city for the MVP and that other 'open' search functionality will be a stretch goal

5. An FYI that the team agrees that the separate page for user is unfortunately out of scope for this MVP as it has to do with the way we are storing data (airtable) and various links between pages. As your app grows, you will definitely need to have a team build a custom database for you as Airtable will not suffice for your long term needs. The team has agreed to render user data with the recommendation for the meantime (as it is not on another page, it is doable).

6. As the team has now started building the project, they are requesting that the Pages document stays stable as they will be working from it. If you have additional ideas that you would like to see implemented in future sprints, I would recommend adding that to  a different document as not to confuse the team.

Thanks Katia!!!

**Comment by KatiaSitspot** [comment]
@teenie-quaggard @aminalakhsham 
I can't attend the call today unfortunately. But here are my main focus points:

1-	Is **flow clear to you and logical**? Especially 2 different routes for adding a recommendation:
•	From the landing page => user fill in the short “sitspot id” form, and then the long recommendation form that corresponds to the business type they have selected 
•	From the individual sitspot page => user doesn’t have to fill in the “sitspot id form” they go straight to fill in the long form
Note: we need to think about how users will be directed from the “sitspot id” form to the long form.

2-	re: **contributor profile** needed to be on a separate page, see note I made in PAGES v7. I count 9 pages in total.

3-	Re: the **individual sitspot page**: we’ll need to do quite a few tests, to see how it looks
•	when users don’t fill in the fields in Typeform that are optional (basically there will be some blanks)
•	to make sure it works for all 3 types of businesses (Stay, eat, shop) as the Typeforms will be slightly different

4-	I am aware that I still need to **create the Typeform** for EAT, and for SHOP. And to enter a few examples in Typeform.
Will crack on today/tomorrow

5-	**Call next week**
Ideally Thursday morning 9.30-12.30am would be good for me

**Comment by KatiaSitspot** [comment]
@aminalakhsham @teenie-quaggard 
FYI the Typeform for EAT/DRINK is now ready. You can access it with my login

**Comment by KatiaSitspot** [comment]
and now the SHOP one is ready. and i have entered a shop entry (Hetu) in Typeform

**Comment by KatiaSitspot** [comment]
Hi @aminalakhsham @teenie-quaggard can you please confirm that all is ok with the Typeform questionnaires i have created? Also, do let me know if you need me to enter some recommendations (there’s currently one : Hetu in shops) and if so tell me which one i should prioritise and your deadline. Thanks

**Comment by aminalakhsham** [comment]
for know, we not seeing the form but good if you enter some recommendations.
about the deadline, I'll let Kristina to talk about that.

**Comment by KatiaSitspot** [comment]
Hi. It’s weird that you can not see those Typeform questionnaires. You can access them using the same login details i had already shared. Please let me know if you can access or if you want me to share my login details with you again

**Comment by aminalakhsham** [comment]
I can access but we will see it today or tomorrow maximum

**Comment by KatiaSitspot** [comment]
@aminalakhsham @teenie-quaggard here is a doc where you will understand how the search by keyword works. **I have linked each keyword with the relevant question/answer in the Typeforms**
[Keywords linked to questions.xlsx](https://github.com/GSG-G7/sitspot/files/3824515/Keywords.linked.to.questions.xlsx)



**Search by keyword process:**
1)	Here’s how I understand you are planning to make the search works:
a.	In Country, user gets a drop down of the countries for which users have entered sitspot. User selects one country
b.	In City, user gets a drop down of the cities for which users have entered sitspot. User selects one city
c.	User selects either Stay, Eat Drink, or Shop
d.	User can also (but not mandatory) further narrow down by selecting some keywords
The search won’t work unless user selects a country. Please note that users might not know which city specifically they want to go to, so this shouldn’t be a mandatory field.

2)	Here’s how the search should work (but this might be a stretch goal?):
a.	User should be able to select 1 country, press search and get all the results = all the sitspot from different types, and from different cities for which the country has been selected
b.	User should be able to select 1 key word, press search and get all the results = all the sitspots from different types, and from different countries for which the keyword has been selected
This is because at the beginning, we will have a limited number of sitspots, and we want to avoid user getting zero result


**Here's the icon for each key word** - if you need them
<img width="759" alt="designed icons" src="https://user-images.githubusercontent.com/56404750/68476342-54055280-0222-11ea-8d34-257d6857206e.png">

**Comment by KatiaSitspot** [comment]
@aminalakhsham @teenie-quaggard 
as promised, you will find 3 entries, 1 for each type of business. As you are managing the form to enter the sitspots' ID, please let me know how you want me to supply these infos.

**Comment by teenie-quaggard** [comment]
Thanks @KatiaSitspot !

**Comment by teenie-quaggard** [comment]
Hi @KatiaSitspot - it looks like there is a live version up at the moment, if you'd like to take a look:
https://sitspot.herokuapp.com/

They are still working on it, so not all the copy has been updated and some of the functionality is still in progress. You can see the initial feedback that I've provided to them here:
https://github.com/GSG-G7/sitspot/issues/86

Feel free to have a look and make some notes on the pages that are working. You are welcome to add a comment to that issue above ^

Either way, let's catch up later today and we can see what they have managed to get through over the course of today. Are you still free to speak around 5?

**Comment by KatiaSitspot** [comment]
Hi Kristina,

 

OK, I will list my comments on issue #86

And I can talk at 5pm.

 

Best

Katia

**Comment by teenie-quaggard** [comment]
Closing this issue as it has become quite big. Will open up new issues for communication.
